### ISSUE TITLE
FR: import/export channels

### ISSUE THREAD

**Issue by Rasterisko** [ultraabox/ultrabox_typescript#226] opened 2024-07-06 20:18 UTC
Hi,

It would be useful to be able to separately export the channels to reuse them in other songs.

**Comment by MainCharacteroftheProblem** [comment] 2024-07-06 22:08
This is a duplicate of #17, closing this

**Comment by MainCharacteroftheProblem** [comment] 2024-07-06 22:09
oops

**Closed by MainCharacteroftheProblem** 2024-07-06 22:09 UTC
Labels: duplicate, enhancement
