### ISSUE TITLE
Fix Song Recovery in the offline version

### ISSUE THREAD

**Issue by moonvixen** [ultraabox/ultrabox_typescript#222] opened 2024-06-09 03:21 UTC
I made a really nice tune but accidentally closed the window and didn't prompt me to save or exit. I brought up the song recovery prompt and although it loads the tune's name (including multiple versions of it), the space where there's usually an <iframe> element on the online version is just black for all of the songs in recovery.

Clearly the app still has the song cached/stored somewhere, but I can't find it in any of the files. Is there some way I can manually extract the song data and put it into online UltraBox (to recover or whatever)?

This was on v2.2.7.
![image](https://github.com/ultraabox/ultrabox_typescript/assets/122327953/b5a6d284-e91a-4d4e-b03f-b3b6a2e55ff0)

**Comment by wdymThisIsntAvailable** [comment] 2024-06-09 03:37
@moonvixen Unless you disabled song data in the URL, try checking your browser history to find the song you were currently making.

**Comment by moonvixen** [comment] 2024-06-09 03:43
It wouldn't be in the browser history - it's in the Offline (.exe) version. Which, from what I can tell, seems to package it's whole own Electron/Chromium instance so it's URL and storage would be exclusive to it.

**Comment by moonvixen** [comment] 2024-06-10 13:59
> @moonvixen Unless you disabled song data in the URL, try checking your browser history to find the song you were currently making.

OK, this took far too long but I've finally figured this out. Electron apps like UB Offline store their data in %APPDATA%, so the folder I was looking for was in C:\Users\Moonvixen\AppData\Roaming\UltraBox Offline.

Within that folder, inside \Local Storage\ there's a directory called \leveldb\. In there, there's a file called "LOG" with no file extension. Opened as a text file, it reads:

`2024/06/09-12:19:38.427 63dc Reusing MANIFEST C:\Users\Moonvixen\AppData\Roaming\UltraBox Offline\Local Storage\leveldb/MANIFEST-000001`
`2024/06/09-12:19:38.429 63dc Recovering log #240`
`2024/06/09-12:19:38.430 63dc Reusing old log C:\Users\Moonvixen\AppData\Roaming\UltraBox Offline\Local Storage\leveldb/000240.log`

I opened the "000240.log" file it lists (all the others are mostly ".ldb") and lo and behold CTRL+F for the name of the tracks reveals the entire track data for the exact song I lost along with it in URL form. Copied that whole URL over into Firefox, replaced the part of the string with the track name "ûu5N0lDo%20You%20Feel%3F%" with "ultraabox.github.io/#u5N0lDo You Feel%3F" so the encoding works. You need to copy from the û (the track name) to the part that has a "]" after the samples - without including the ]:
![image](https://github.com/ultraabox/ultrabox_typescript/assets/122327953/5fbf8b3f-48d6-4b78-acf7-46dae8412a54)

Very happy I could figure this out as I thought I'd just lose it :) I'm sure it's not as difficult as I just made it out to be, but it's not really documented or obvious for average end-users so hopefully this might help someone out in the future with a similar problem.

**Comment by moonvixen** [comment] 2024-06-10 14:59
v2.2.9 (current) still appears to suffer from this bug so I'll keep this issue open for the time being - until then, the above method using the online UltraBox seems to work as a workaround for the bugged file recovery prompt.

**Comment by MainCharacteroftheProblem** [comment] 2024-06-10 18:46
If I had to guess, I'd say that is caused by the same problem that caused the song player to not work

**Comment by moonvixen** [comment] 2024-06-11 01:13
That was my assumption as well - I hadn't noticed the File Recovery prompt not working earlier because it's not the type of thing you'd really access that often... given the actual storage of the recovery data seems to work fine though, the <iframe> with the link to it is probably less important.

**Comment by MainCharacteroftheProblem** [comment] 2024-07-11 16:38
Fixed in the latest commit, closing

**Comment by MainCharacteroftheProblem** [comment] 2024-07-11 16:39
Should I release a 2.2.9 bugfix build of UB Offline?

**Closed by MainCharacteroftheProblem** 2024-07-11 16:38 UTC
Labels: bug, offline version
